image: gitlab/dind

# Use the OverlayFS driver for improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind



before_script:
    -  docker info
    -  sudo apt-get update
    -  sudo apt-get -y install docker-engine=1.7.1-0~trusty
    -  sudo curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
    -  sudo chmod +x /usr/local/bin/docker-compose
    -  docker-compose -f stack-docker/docker-compose.yml up -d

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - release
  - deploy


build:
  stage: build
  variables:
    NODE_ENV: "development"
  script:
    -  npm install
    -  npm install strapi@alpha -g
    -  cd public/frontend && npm install
    -  cd public/frontend && npm run build



