image: node:9

cache:
  paths:
    - node_modules/

stages:
  - test
  - development
  - production


before_script:
  - 'cd stack-docker'
  - 'docker-compose up -d'

setup_strapi:
  stage: test
  script:
   - npm install
   - npm install strapi@alpha -g
  tags:
    - docker

setup_frontend:
  stage: test
  script:
   - 'cd public/frontend'
   - npm install
   - npm run build
  tags:
    - docker

