image: node:9

cache:
  paths:
  - node_modules/

stages:
  - test
  - build

before_script:
  - npm install strapi@alpha -g

test_backend:
  stage: test
  script:
   - npm install
  tags:
    - docker

test_db:
  stage: test
  services:
    - mongo
  script:
   - strapi start
  tags:
    - docker

test_frontend:
  stage: test
  script:
    - cd public/frontend
    - npm install
    - npn run test

