image: node:9

cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy


test_backend:
  stage: test
  script:
   - npm install strapi@alpha -g
  tags:
    - docker


test_frontend:
  stage: test
  script:
    - cd public/frontend
    - npm install
    - npn run test


