image: docker:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - release
  - deploy


build:
  stage: build
  image: node:9
  variables:
    NODE_ENV: "development"
  before_script:
    -  docker info
    -  docker-compose -f stack-docker/docker-compose.yml up -d
    -  npm install
    -  npm install strapi@alpha -g
    -  cd public/frontend && npm install
  script:
    -  cd public/frontend && npm run build
