image: docker:dind

# Use the OverlayFS driver for improved performance.
variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind



before_script:
    -  docker info
    -  docker-compose -f stack-docker/docker-compose.yml up -d

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - release
  - deploy


build:
  stage: build
  variables:
    NODE_ENV: "development"
  script:
    -  npm install
    -  npm install strapi@alpha -g
    -  cd public/frontend && npm install
    -  cd public/frontend && npm run build



