filebeat.config:
  prospectors:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- decode_json_fields:
    fields: ['path', 'value']
    process_array: true
    overwrite_keys: false

filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/logs/websocket.log
  document_type: json
  fields:
      type: osquery_json
      codec: json
  json.message_key: log

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  username: elastic
  password: changeme
#output.logstash:
#  hosts: ["logstash:5044"]
